# Generated by Django 4.1.3 on 2022-11-20 19:52

import IT_TaskPortal.accounts.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_appuser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), IT_TaskPortal.accounts.validators.validate_only_letters], verbose_name='Име /First name'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), IT_TaskPortal.accounts.validators.validate_only_letters], verbose_name='Фамилия /Family name'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='shor', to='accounts.department', verbose_name='Избери Дирекция/Choose department'),
        ),
    ]
