# Generated by Django 4.1.3 on 2022-11-20 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_appuser_email_alter_appuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='user_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='shor', to='accounts.department', verbose_name='Дирекция (Department)'),
        ),
    ]
