# Generated by Django 4.1.3 on 2022-11-26 19:39

import IT_TaskPortal.accounts.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0002_alter_employees_employee_dekt'),
        ('accounts', '0008_alter_appuser_first_name_alter_appuser_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TaskForNewWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_first_name_bg', models.CharField(max_length=30, verbose_name='Име на български| First name')),
                ('worker_last_name_bg', models.CharField(max_length=30, verbose_name='Фамилия | Family name')),
                ('worker_first_name_en', models.CharField(max_length=30, verbose_name='Име на латиница| First name')),
                ('worker_last_name_en', models.CharField(max_length=30, verbose_name='Фамилия на латиница| Family name')),
                ('worker_from_data', models.DateField(verbose_name='Дата на постъпване| Data of entry')),
                ('worker_division', models.CharField(max_length=40, verbose_name='Отдел| Division')),
                ('worker_position', models.CharField(max_length=50, verbose_name='Длъжност| Position')),
                ('worker_phone_number', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(9), IT_TaskPortal.accounts.validators.validate_only_digits], verbose_name='Мобиле или Стационарен номер| Mobile or work number')),
                ('office_number', models.CharField(max_length=50, verbose_name='Помещение| Room')),
                ('rights_same_as_worker_name', models.CharField(blank=True, max_length=50, verbose_name='Права сходни със служител| Rights similar to colleague')),
                ('create_user_account', models.BooleanField(verbose_name='Потребителски акаунт| User account')),
                ('create_user_email', models.BooleanField(verbose_name='Електронна поща | Email')),
                ('vpn_from_work_laptop', models.BooleanField(verbose_name='VPN от служебен лаптоп| VPN from work laptop')),
                ('vpn_from_private_comp_to_office_com', models.BooleanField(verbose_name='VPN достъп от личен до служебен офис компютър | VPN from private to work computer')),
                ('internet_access', models.BooleanField(verbose_name='Интернет| Internet')),
                ('phone_line', models.BooleanField(verbose_name='Телефонна линия| Phone line')),
                ('computer', models.BooleanField(verbose_name='Настолен компютър| Desktop computer')),
                ('laptop', models.BooleanField(verbose_name='Лаптоп| Laptop')),
                ('laser_printer_scanner', models.BooleanField(verbose_name='Лазарен принтер| Laser Printer')),
                ('matrix_printer', models.BooleanField(verbose_name='Матричен принтер| Matrix printer')),
                ('color_printing_possibility', models.BooleanField(verbose_name='Цветно копиране| Color print')),
                ('microsoft_office', models.BooleanField(verbose_name='Microsoft Office')),
                ('eventis', models.BooleanField(verbose_name='Деловодна програма| Eventis')),
                ('sonita', models.BooleanField(verbose_name='Сонита| Sonita')),
                ('ahm', models.BooleanField(verbose_name='Полетна информация| AHM')),
                ('omeks', models.BooleanField(verbose_name='Омекс| Omeks')),
                ('procurement_software', models.BooleanField(verbose_name='Софтуер за поръчки| Software for procurement')),
                ('legal_software', models.BooleanField(verbose_name='Юридически софтуер| Leagel software')),
                ('landline_phone', models.BooleanField(verbose_name='Стационарен телефон| Stationary Phone')),
                ('dekt_mobile_phone', models.BooleanField(verbose_name='Дект| Dect')),
                ('mobile_phone', models.BooleanField(verbose_name='Мобилен телефон| Mobile phone')),
                ('tetra_station', models.BooleanField(verbose_name='Тетра станция| Tetra')),
                ('remarks', models.TextField(blank=True, max_length=200, verbose_name='Коментар | Remarks')),
                ('status', models.CharField(choices=[('pending', 'Очаква изпълнение'), ('partial_executed', 'Частично изпълненa'), ('executed', 'Приключена')], default='Очаква изпълнение', max_length=50, verbose_name='Статус| State')),
                ('data_of_creation', models.DateField(auto_now=True, verbose_name='Дата на създаване| Data_of_creation')),
                ('data_of_execution', models.DateField(null=True, verbose_name='Дата на приключване| Data of execution')),
                ('employee_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.employees', verbose_name='Отговорно лице| Person responsible')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Зъздал заявката | Request created by')),
                ('work_place_building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.buildings', verbose_name='Изберете сфрадата в която работите| Choose workplace building')),
                ('worker_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department', verbose_name='Дирекция| Department')),
            ],
        ),
    ]
