# Generated by Django 4.1.3 on 2022-11-28 11:11

import IT_TaskPortal.accounts.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfornewworker',
            name='data_of_execution',
            field=models.DateField(blank=True, null=True, verbose_name='Дата на приключване| Data of execution'),
        ),
        migrations.AlterField(
            model_name='taskfornewworker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Създал заявката | Request created by'),
        ),
        migrations.AlterField(
            model_name='taskfornewworker',
            name='vpn_from_work_laptop',
            field=models.CharField(choices=[('pending', 'Очаква изпълнение'), ('partial_executed', 'Частично изпълненa'), ('executed', 'Приключена')], max_length=50, verbose_name='VPN от служебен лаптоп| VPN from work laptop'),
        ),
        migrations.AlterField(
            model_name='taskfornewworker',
            name='work_place_building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.buildings', verbose_name='Изберете сградата в която работите| Choose workplace building'),
        ),
        migrations.AlterField(
            model_name='taskfornewworker',
            name='worker_first_name_bg',
            field=models.CharField(max_length=30, verbose_name='Име на кирилица| First name'),
        ),
        migrations.AlterField(
            model_name='taskfornewworker',
            name='worker_last_name_bg',
            field=models.CharField(max_length=30, verbose_name='Фамилия на кирилица| Family name'),
        ),
        migrations.AlterField(
            model_name='taskfornewworker',
            name='worker_phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(9), IT_TaskPortal.accounts.validators.validate_only_digits], verbose_name='Мобилен или стационарен  телефонен номер| Mobile or work number'),
        ),
    ]
