# Generated by Django 4.1.3 on 2022-11-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_taskfornewworker_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildings',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
