# Generated by Django 4.1.3 on 2022-12-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_buildings_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildings',
            name='file',
        ),
        migrations.AddField(
            model_name='buildings',
            name='drawing_file',
            field=models.FileField(blank=True, upload_to='drawings'),
        ),
    ]
