# Generated by Django 4.1.3 on 2022-12-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_buildings_file_buildings_drawing_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfornewworker',
            name='rights_same_as_worker_name',
            field=models.TextField(blank=True, max_length=300, verbose_name='Права сходни със служител(достъп до ресурси| Rights similar to colleague(access to recourses)'),
        ),
    ]
