# Generated by Django 4.1.3 on 2022-12-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_taskfornewworker_rights_same_as_worker_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskfornewworker',
            name='internet_access',
        ),
        migrations.RemoveField(
            model_name='taskfornewworker',
            name='phone_line',
        ),
        migrations.AddField(
            model_name='taskfornewworker',
            name='access_to_group_mail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Достъп но групов имейл | Join to email group'),
        ),
        migrations.AddField(
            model_name='taskfornewworker',
            name='access_to_read',
            field=models.CharField(blank=True, choices=[('yes', 'да/yes'), ('no', 'не/no')], max_length=12, null=True, verbose_name='Права само за четене | Rights to read only'),
        ),
        migrations.AddField(
            model_name='taskfornewworker',
            name='access_to_write',
            field=models.CharField(blank=True, choices=[('read_only', 'без право да записва/without right to write'), ('write_read', 'може да прави записи /can write in directory')], max_length=15, verbose_name='Права да записва | Rights to write'),
        ),
        migrations.AddField(
            model_name='taskfornewworker',
            name='adobe_software',
            field=models.BooleanField(blank=True, null=True, verbose_name='adobe Pro'),
        ),
        migrations.AddField(
            model_name='taskfornewworker',
            name='avtoservice',
            field=models.BooleanField(blank=True, null=True, verbose_name='Avtoservice'),
        ),
        migrations.AddField(
            model_name='taskfornewworker',
            name='data_of_partial_finish',
            field=models.DateField(blank=True, null=True, verbose_name='Дата на частично изпълнение'),
        ),
        migrations.AddField(
            model_name='taskfornewworker',
            name='deepl',
            field=models.BooleanField(blank=True, null=True, verbose_name='Deepl'),
        ),
        migrations.AddField(
            model_name='taskfornewworker',
            name='fuels',
            field=models.BooleanField(blank=True, null=True, verbose_name='Fuels'),
        ),
        migrations.AddField(
            model_name='taskfornewworker',
            name='is_new_worker',
            field=models.CharField(choices=[('yes', 'да/yes'), ('no', 'не/no')], default='no', max_length=15, verbose_name='Служителят е нов потребител | New user'),
        ),
        migrations.AddField(
            model_name='taskfornewworker',
            name='monitor',
            field=models.BooleanField(blank=True, null=True, verbose_name='Монитор | Monitor'),
        ),
        migrations.AddField(
            model_name='taskfornewworker',
            name='nanocad',
            field=models.BooleanField(blank=True, null=True, verbose_name='NanoCad'),
        ),
        migrations.AddField(
            model_name='taskfornewworker',
            name='scaner',
            field=models.BooleanField(blank=True, null=True, verbose_name='Скенер| Scanner'),
        ),
        migrations.AddField(
            model_name='taskfornewworker',
            name='sonita_bi',
            field=models.BooleanField(blank=True, null=True, verbose_name='SioProBI'),
        ),
        migrations.AddField(
            model_name='taskfornewworker',
            name='worker_second_name_bg',
            field=models.CharField(default='Напишете име', max_length=30, verbose_name='Бащино име кирилица| Second name'),
        ),
        migrations.AlterField(
            model_name='taskfornewworker',
            name='create_user_account',
            field=models.BooleanField(verbose_name='Създаване на нов потребител в системата| Create new User account'),
        ),
        migrations.AlterField(
            model_name='taskfornewworker',
            name='create_user_email',
            field=models.BooleanField(blank=True, verbose_name='Електронна поща | Email'),
        ),
        migrations.AlterField(
            model_name='taskfornewworker',
            name='eventis',
            field=models.BooleanField(verbose_name='Eventis'),
        ),
        migrations.AlterField(
            model_name='taskfornewworker',
            name='laser_printer_scanner',
            field=models.BooleanField(verbose_name='Черно-бял печат| Black and White Printer'),
        ),
        migrations.AlterField(
            model_name='taskfornewworker',
            name='legal_software',
            field=models.BooleanField(verbose_name='Lakorda'),
        ),
        migrations.AlterField(
            model_name='taskfornewworker',
            name='omeks',
            field=models.BooleanField(verbose_name='Omeks'),
        ),
        migrations.AlterField(
            model_name='taskfornewworker',
            name='rights_same_as_worker_name',
            field=models.TextField(blank=True, max_length=100, verbose_name='Права сходни със служител(Достъп до фирмени ресурси/папки| Rights similar to :(access to folders)'),
        ),
        migrations.AlterField(
            model_name='taskfornewworker',
            name='sonita',
            field=models.BooleanField(verbose_name='SioPro'),
        ),
        migrations.AlterField(
            model_name='taskfornewworker',
            name='vpn_from_private_comp_to_office_com',
            field=models.BooleanField(verbose_name='Отдалечен достъп до фирмената мрежа oт личен компютър | VPN from private to work domain system'),
        ),
        migrations.AlterField(
            model_name='taskfornewworker',
            name='vpn_from_work_laptop',
            field=models.CharField(choices=[('yes', 'да/yes'), ('no', 'не/no')], max_length=50, verbose_name='Отдалечен достъп до фирмената мрежа от служебен лаптоп| VPN from work laptop'),
        ),
    ]
