# Generated by Django 4.1.3 on 2022-12-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_taskfornewworker_internet_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfornewworker',
            name='vpn_from_work_laptop',
            field=models.BooleanField(verbose_name='Отдалечен достъп до фирмената мрежа от служебен лаптоп| VPN from work laptop'),
        ),
    ]
