# Generated by Django 4.1.3 on 2022-12-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_taskfornewworker_vpn_from_work_laptop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskfornewworker',
            name='access_to_read',
        ),
        migrations.RemoveField(
            model_name='taskfornewworker',
            name='access_to_write',
        ),
        migrations.AddField(
            model_name='taskfornewworker',
            name='access_to_read_write',
            field=models.CharField(blank=True, choices=[('read_only', 'без право да записва/without right to write'), ('write_read', 'може да прави записи /can write in directory')], max_length=12, null=True, verbose_name='Права само за четене | Rights to read only'),
        ),
    ]
