# Generated by Django 4.1.3 on 2022-12-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_taskfornewworker_color_copy_possibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfornewworker',
            name='rights_same_as_worker_name',
            field=models.CharField(blank=True, max_length=180, verbose_name='Права сходни със служител(Достъп до фирмени ресурси/папки| Rights similar to :(access to folders)'),
        ),
    ]
