# Generated by Django 4.1.3 on 2022-12-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_taskfornewworker_color_copy_possibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfornewworker',
            name='color_copy_possibility',
            field=models.BooleanField(blank=True, verbose_name='Цветно копиране| Color copy'),
        ),
    ]
