# Generated by Django 4.1.3 on 2022-12-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_taskfornewworker_color_copy_possibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfornewworker',
            name='color_copy_possibility',
            field=models.BooleanField(blank=True, default=False, verbose_name='Цветно копиране| Color copy'),
        ),
        migrations.AlterField(
            model_name='taskfornewworker',
            name='monitor',
            field=models.BooleanField(blank=True, default=False, verbose_name='Монитор | Monitor'),
        ),
        migrations.AlterField(
            model_name='taskfornewworker',
            name='scaner',
            field=models.BooleanField(blank=True, default=False, verbose_name='Скенер| Scanner'),
        ),
    ]
