# Generated by Django 4.1.3 on 2022-12-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_taskfornewworker_color_copy_possibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfornewworker',
            name='adobe_software',
            field=models.BooleanField(default=False, verbose_name='adobe Pro'),
        ),
        migrations.AlterField(
            model_name='taskfornewworker',
            name='avtoservice',
            field=models.BooleanField(default=False, verbose_name='Avtoservice'),
        ),
        migrations.AlterField(
            model_name='taskfornewworker',
            name='deepl',
            field=models.BooleanField(default=False, verbose_name='Deepl'),
        ),
        migrations.AlterField(
            model_name='taskfornewworker',
            name='fuels',
            field=models.BooleanField(default=False, verbose_name='Fuels'),
        ),
        migrations.AlterField(
            model_name='taskfornewworker',
            name='nanocad',
            field=models.BooleanField(default=False, verbose_name='NanoCad'),
        ),
        migrations.AlterField(
            model_name='taskfornewworker',
            name='sonita_bi',
            field=models.BooleanField(blank=True, default=False, verbose_name='SioProBI'),
        ),
    ]
