# Generated by Django 4.1.3 on 2022-12-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_taskfornewworker_worker_second_name_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfornewworker',
            name='worker_second_name_bg',
            field=models.CharField(max_length=30, null=True, verbose_name='Бащино име кирилица| Second name'),
        ),
    ]
