# Generated by Django 4.1.3 on 2022-12-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_taskfornewworker_worker_second_name_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfornewworker',
            name='is_new_worker',
            field=models.BooleanField(blank=True, verbose_name='Служителят е нов потребител | New user'),
        ),
    ]
