# Generated by Django 4.1.3 on 2022-12-04 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_employees_employee_dekt'),
        ('tasks', '0020_alter_taskfornewworker_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelecomContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=20, verbose_name='Номер на договор')),
                ('contractor_name', models.CharField(max_length=50, verbose_name='Име на фирма')),
                ('contractor_bulstat', models.CharField(blank=True, max_length=20)),
                ('person_for_contact', models.CharField(blank=True, max_length=60, verbose_name='Лице за контакт')),
                ('contractor_email', models.EmailField(blank=True, max_length=254, verbose_name='Email за контакт')),
                ('contractor_phone', models.CharField(blank=True, max_length=10, verbose_name='Телефон на лице за контакт')),
                ('data_from', models.DateField(verbose_name='Начална дата на договора')),
                ('end_data_of_contract', models.DateField(verbose_name='Дата на изтичане на договора')),
                ('description', models.CharField(max_length=300, verbose_name='Предмет на договора')),
                ('contract_file', models.FileField(blank=True, upload_to='telecom/contracts')),
                ('anex_one', models.CharField(blank=True, max_length=20)),
                ('anex_one_file', models.FileField(blank=True, upload_to='telecom/anex')),
                ('anex_two', models.CharField(blank=True, max_length=20)),
                ('anex_two_file', models.FileField(blank=True, upload_to='telecom/anex')),
                ('anex_three', models.CharField(blank=True, max_length=20)),
                ('anex_three_file', models.FileField(blank=True, upload_to='telecom/anex')),
                ('prise_contract', models.CharField(blank=True, max_length=6)),
                ('prise_last_anex', models.CharField(blank=True, max_length=6)),
                ('person_involved', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.employees', verbose_name='Отговорно лице| Person responsible')),
            ],
        ),
    ]
