# Generated by Django 4.1.3 on 2022-12-04 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_employees_employee_dekt'),
        ('tasks', '0021_telecomcontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTelekomTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_of_creation', models.DateField(auto_now=True, verbose_name='Дата на създаване| Data_of_creation')),
                ('contractor_name', models.CharField(max_length=50, verbose_name='Име на фирма подател')),
                ('request_paper', models.FileField(blank=True, upload_to='telecom/request_papers')),
                ('protocol_for_execution', models.FileField(blank=True, upload_to='protocols')),
                ('new_access_points', models.BooleanField(verbose_name='Точки за достъп')),
                ('point_number', models.IntegerField(blank=True, verbose_name='Брой точки')),
                ('data_of_execution', models.DateField(blank=True, verbose_name='Дата на изпълнение')),
                ('remarks_from_executor', models.TextField(blank=True, max_length=300, verbose_name='Коментар по изпълнението')),
                ('for_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.telecomcontract', verbose_name='Към договор')),
                ('responsible_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.employees', verbose_name='Отговорно лице| Person responsible')),
            ],
        ),
    ]
