# Generated by Django 4.1.3 on 2022-12-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_externaltelekomtasks_office_descropton_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltelekomtasks',
            name='data_of_execution',
            field=models.DateField(blank=True, null=True, verbose_name='Дата на изпълнение'),
        ),
    ]
