# Generated by Django 4.1.3 on 2022-11-25 14:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('employee_email', models.EmailField(max_length=254)),
                ('employee_dekt', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9, 'Невалиден формат')])),
                ('employee_position', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='team.positions')),
            ],
        ),
    ]
