# Generated by Django 4.1.3 on 2022-11-25 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employee_dekt',
            field=models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4, 'Невалиден формат')]),
        ),
    ]
